[package]
name = "nn_tools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
ndarray = "0.15.3"
ndarray-stats = "0.5.0"
ndarray-rand = "0.14.0"
rand = "0.8.4"
mnist = "0.4.1"
