name: Rust

on: pull_request
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ./nn-tools
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./nn-tools
